ANT	= env LC_ALL=en ant

all:
	$(ANT) all

clean:
	$(ANT) clean

test1:
	$(ANT) test1

test2:
	$(ANT) test2

test3:
	$(ANT) test3

test4:
	$(ANT) test4

install:
	$(ANT) install

doc:
	$(ANT) doc

zip:
	$(ANT) zip
